POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "2",
    "number": "123"
}

###
POST https://phonebook8899.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "2",
    "number": "123"
}